services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: OpenRental_2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
  openrental:
    image: openrental-vehicles:1.0
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"