spring:
  application:
    name: openrental-vehicles
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driverClassName: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
          jwk-set-uri: ${KEYCLOAK_JWKS_URI}
jwt:
  auth:
    converter:
      resource-id: openrental-vehicles
      principle-attribute: preferred_username