spring:
  application:
    name: openrental-vehicles
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driverClassName: org.postgresql.Driver